name: combine
description: A Flutter package which allows you to work with MethodChannels in Isolate. Also it provides simplified multiplatform Isolate API.
version: 0.1.2
homepage: https://github.com/Maksimka101/combine
repository: https://github.com/Maksimka101/combine

environment:
  sdk: ">=2.16.2 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.9
  mocktail: ^0.3.0
  meta: ^1.7.0

flutter:
